$title@: The AMPize project overview
rows:
    - template: col1
      columns:
        - template: hero
          title@: Embrace the future web
          titleclass: green
          content@: <p class="mb2"><a href="http://www.ampproject.com" target="_blank">AMP</a> is an open-source initiative aiming to make the web better for all. The project enables the creation of websites and ads that are consistently fast, beautiful and high-performing across devices and distribution platforms.</p><p>AMPize is a complete, straightforward and plug&play ecosystem to publish and monetize existing contents leveraging the power of AMP </p>
    - template: col2
      columns:
        - template: text
          title@: A collaborative project
          content@: Just like the AMP project, AMPize embodies the values of open development, sharing and co-operation, and was initiated by a consortium of international media companies including French, Belgian and British publishers.
        - template: text
          title@: Supported by the Google DNI Innovation Fund
          content@: The AMPize project has been awarded during the second round of funding from <a href="https://digitalnewsinitiative.com/" target="_blank">Google's Digital News Initiative</a>, a fund created to support and stimulate innovation in digital news journalism.
    - template: col1
      columns:
        - template: hero
          title@: AMP for all
          content@: <p class="mb2">for everyone, open-source, simple, affordable, plug&play, any data source, onpremise & cloud, with free PLAN</p>
          acta2@: Discover AMPize Features
          acta2_url: /about/features.yaml
